version: '3'
services: 
    web:
        container_name: boto_php
        build: ./Dockerfiles/php
        volumes: 
            - .:/var/www/boto
        restart: on-failure
        tty: true
        ports:
        - 8585:8585
        depends_on:
          - db
          - redis
    redis:
        container_name: boto_redis
        image: redis
        restart: always
    db:
        container_name: boto_postgres
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
    adminer:
        container_name: boto_adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
          - db
    supervisor:
        container_name: boto_supervisor
        build: ./Dockerfiles/supervisor
        volumes:
            - .:/app
        restart: on-failure
        tty: true
        depends_on:
          - web
    composer:
        container_name: boto_composer
        build: ./Dockerfiles/composer
        volumes:
            - .:/app
        tty: true
        restart: on-failure
        command: ["composer", "install"]
